CREATE TABLE CURRENCY_FRAME
(
    ID                    BIGSERIAL NOT NULL,
    FIRST_CURRENCY        VARCHAR(255) NOT NULL,
    SECOND_CURRENCY       VARCHAR(255) NOT NULL,
    BUY_PRICE             NUMERIC NOT NULL,
    SELL_PRICE            NUMERIC NOT NULL,
    SOURCE                VARCHAR(255) NOT NULL,
    COUNTRY               VARCHAR(255) NOT NULL,
    DATE                  TIMESTAMP,
    MOVING_AVERAGE        NUMERIC NOT NULL,
    PRIMARY KEY (ID)
);